# # Auto-run tests on push/PR to ensure nothing breaks.
# # .github/workflows/ci.yml

# name: Python CI

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Set up Python
#       uses: actions/setup-python@v5
#       with:
#         python-version: '3.12' # Use a specific Python version, e.g., 3.12 or 3.x
#         cache: 'pip' # Cache pip dependencies

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         # Install main requirements
#         pip install -r requirements.txt
#         # Install development/test requirements
#         pip install -r requirements-dev.txt

#     - name: Set PYTHONPATH
#       # Set PYTHONPATH to the current working directory to ensure 'src' module is found
#       run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

#     - name: Run tests with pytest
#       run: |
#         # Change to the project root directory where the 'tests' folder is located
#         pytest -v

#     - name: Run linting with Flake8
#       run: |
#         flake8 src/ tests/

#     - name: Check code formatting with Black
#       run: |
#         # --check makes Black only report errors, not fix them
#         # --diff shows the differences if files are not formatted correctly
#         black --check --diff src/ tests/

#     - name: Check import sorting with isort
#       run: |
#         # --check-only makes isort only report errors, not fix them
#         isort --check-only src/ tests/

name: Production

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Cloning
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
#intentationss
  lint-and-test:
    needs: build
    runs-on: ubuntu-latest
    env: # keys for apis
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
      PINECONE_INDEX: ${{ secrets.PINECONE_INDEX }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 pytest coverage
          

      #- name: Run Flake8
       # run: flake8 .

      - name: Run Pytest with Reports
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          # pytest --junitxml=pytest-report.xml
          # coverage run -m pytest
          # coverage xml -o coverage.xml
      - name: setting up sonar
        uses: warchant/setup-sonar-scanner@v7    
      - name: Run SonarCloud Scan (fallback if no coverage)
        run: |
          if [ -f coverage.xml ]; then
            echo "✅ Found coverage.xml. Running SonarScanner with coverage..."
            sonar-scanner \
              -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}\
              -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
              -Dsonar.sources=. \
              -Dsonar.coverageReportPaths=coverage.xml \
              -Dsonar.python.xunit.reportPath=pytest-report.xml
          else
            echo "⚠️ coverage.xml not found. Running SonarScanner without coverage..."
            sonar-scanner \
              -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
              -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
              -Dsonar.sources=.
          fi
